import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "../components/HomePage";
import About from "../components/About";
import Team from "../components/team";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>CodeZen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <HomePage />
     <About />
     <Team />
    </div>
  );
};

export default Home;
